# Generated by Django 4.0.3 on 2023-05-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='empty', max_length=50, verbose_name='User login')),
                ('uid', models.CharField(default='empty', max_length=50, verbose_name='User PC ID')),
                ('key', models.CharField(default='empty', max_length=50, verbose_name='License key')),
                ('code', models.CharField(default='empty', max_length=50, verbose_name='Activation code')),
            ],
        ),
    ]
